### PR TITLE
feat(authelia): added vault secret template for KV v1

### PR DESCRIPTION
**Pull request by elcomtik**
This is a proposal for templating secrets like mentioned at https://github.com/authelia/chartrepo/issues/12#issuecomment-811859226

### CODE REVIEW

**Comment by elcomtik** [comment]
@james-d-elliott what do you think about this solution? This is my first helm chart code, so there may be some imperfections.

How would we define usage value and logic for KV v2 secret engine?

**Comment by james-d-elliott** [comment]
@elcomtik I like it, from what I can tell if a user defines templateValue then it overrides the autogenerated method. Maybe we should rename `templateValue` to `templateOverride`? Thoughts?

**Comment by james-d-elliott** [comment]
Also ideally if it works for you then it's good in my eyes, we can adjust it in time as other users utilize it and want something more/have issues.

We allow people to add their own annotations anyway via `secret.annotations` in the instance they use vault-injector which means they have a fair level of customization.

**Comment by elcomtik** [comment]
> @elcomtik I like it, from what I can tell if a user defines templateValue then it overrides the autogenerated method. Maybe we should rename `templateValue` to `templateOverride`? Thoughts?

I think this naming doesn't matter. The purpose is documented in comments also.

**Comment by james-d-elliott** [comment]
> 
> 
> > @elcomtik I like it, from what I can tell if a user defines templateValue then it overrides the autogenerated method. Maybe we should rename `templateValue` to `templateOverride`? Thoughts?
> 
> I think this naming doesn't matter. The purpose is documented in comments also.

That's fine by me. As soon as you think it's ready to test and you mark it reeady for review I can merge this.

**Comment by elcomtik** [comment]
I added morr comments to document values and changed some values defaults for vault path. It's ready to review.

**Review by james-d-elliott — APPROVED** [review]
LGTM

**Comment by elcomtik** [comment]
Thanks

**Comment by elcomtik** [comment]
@james-d-elliott it didn't propagated to chart repo. Is it because of failed test?

**Comment by james-d-elliott** [comment]
Ah may have failed to push the index, thought I fixed it and didn't check

**Comment by elcomtik** [comment]
Thanks

**Pull request merged**
