### PR TITLE
feat: v4.38.0

### PR DESCRIPTION
**Pull request by james-d-elliott**
This is a work in progress chart version for 4.38.0 (chart version will be 0.9.0 and a BREAKING CHANGE). Public discussion is welcome in [this thread](https://github.com/authelia/chartrepo/discussions/220).

### CODE REVIEW

**Comment by djjudas21** [comment]
@james-d-elliott Do you have a timeline for releasing v4.38.0? Thanks :slightly_smiling_face:

**Comment by james-d-elliott** [comment]
We're looking for feedback on the chart, including the particular elements they are using, the accuracy of the breaking changes [listed here](https://github.com/authelia/chartrepo/blob/dbea6af7e75f27070f12b8ae85c19cf86f2c311f/charts/authelia/BREAKING.md#090), and the consistency of the new format for secrets.

**Comment by autarchprinceps** [comment]
Failed to pull image "ghcr.io/authelia/authelia:v4.38.6"
Looking at the container registry, I think you need to remove the v from the tags

**Comment by james-d-elliott** [comment]
Fixed, testing value made it into the chart whoops! However I'd prefer to keep feedback in this thread if possible: https://github.com/authelia/chartrepo/discussions/220

**Comment by james-d-elliott** [comment]
Merging this as a beta.

**Pull request merged**
