### PR TITLE
Update configMap.yaml

### PR DESCRIPTION
**Pull request by rarosalion**
Enable disabling of tls on mysql/postgresql

### CODE REVIEW

**Comment by rarosalion** [comment]
In case it's not clear from the code changes, for both mysql and postgresql (and, possibly other places?), the "tls:" block in the ConfigMap isn't optional, and forces authelia to try to use tls (even if tls.enabled=false). This change allows the tls.enabled=false setting to take effect.

**Review by james-d-elliott — CHANGES_REQUESTED** [review]
LGTM, just need to bump the chart version.

**Comment by rarosalion** [comment]
I think I've done that right. Let me know if you need anything else to get it merged.

**Comment by james-d-elliott** [comment]
You did not sure how but this already is in master.

**Pull request closed without merging**
